[build]
  command = "npm run build"
  publish = "build"

# Regla de redirecci√≥n para forzar HTTPS y evitar duplicados www/no-www
# Esto redirige todo lo que llegue a www hacia el dominio principal
[[redirects]]
  from = "https://www.somos1egacy.com/*"
  to = "https://somos1egacy.com/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = "build"